# Generated by Django 6.1.1 on 2026-10-02 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_task_category_task_status_alter_task_endtime_and_more'),
        ('room', '0006_add_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room'),
        ),
    ]
