# Generated by Django 6.1.1 on 2026-09-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
