# Generated by Django 6.1.1 on 2026-09-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, default='available', max_length=20),
        ),
    ]
