# Generated by Django 6.1.1 on 2026-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_add_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservices',
            name='servicesType',
            field=models.CharField(choices=[('Food', 'Food'), ('Cleaning', 'Cleaning'), ('Technical', 'Technical'), ('Amenities', 'Amenities')], max_length=20),
        ),
    ]
